### ISSUE TITLE
"Returning BLANK is better because report visuals—by default—eliminate groupings when summarizations are BLANK"

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/query-docs#101]
https://learn.microsoft.com/en-us/dax/best-practices/dax-divide-function-operator

I don't think this is objectively true or true in all situations.  Yes, it will reduce the number of groupings. 

What about other uses, like showing the total of values in a matrix? By default, columns with a blank value will not show a total. 
Yes, there are workarounds for that, but for that use case, returning 0 might be the best option. 

Here is another example where you probably would not want to return BLANK:
https://radacad.com/replace-blank-with-zero-in-power-bi-visuals-such-as-card

I think it is useful to understand the implications of replacing blank with another value, but don't agree that returning BLANK is always better. To me, the statement "Returning BLANK is better..." means that it is always better in all situations.

Also, I do really appreciate the Microsoft CAT team publishing this type of guidance/ best practices!

**Comment by Minewiskan** [comment]
@peter-myers
