### ISSUE TITLE
Repeating "reliability"

### ISSUE THREAD

**Issue by marcvanbreemen** [MicrosoftDocs/query-docs#38]
"Reliability" is mentioned twice:

"Using variables in your DAX formulas can help you write more complex and efficient calculations. Variables can improve performance `and reliability, and readability`, and reduce complexity."

**Comment by JasonWHowell** [comment]
@Minewiskan seems like an easy fix to make, but we'd have to search to see which page the problem is on.

**Comment by JasonWHowell** [comment]
Maybe from page: https://learn.microsoft.com/en-us/dax/best-practices/dax-variables

**Comment by Minewiskan** [comment]
@marcvanbreemen - Reliability is not repeated here. That sentence, however, still does not read well. We'll make a change. Thanks for pointing it out.
