### ISSUE TITLE
Hard to read / possible incorrect description of YoY expression

### ISSUE THREAD

**Issue by marcvanbreemen** [MicrosoftDocs/query-docs#39]
The docs shows this text:

"The formula for YoY sales growth is: period sales fewer sales for the same period last year, divided by sales for the same period last year."

Shouldn't this be something like this?:

"The formula for YoY sales growth is: period sales `minus` sales for the same period last year, divided by sales for the same period last year."

**Comment by JasonWHowell** [comment]
@marcvanbreemen Can you please tell us which page you are referring to?

**Comment by JasonWHowell** [comment]
I think it might be related to DAX page: https://learn.microsoft.com/en-us/dax/best-practices/dax-variables

**Comment by Minewiskan** [comment]
@marcvanbreemen - You are correct. Thanks for pointing this out. We'll make a change that will appear live later today.
