### ISSUE TITLE
Subject about EARLIER could be improved

### ISSUE THREAD

**Issue by marcvanbreemen** [MicrosoftDocs/query-docs#40]
The subject about EARLIER would be much clearer if you would explain that the FILTER function is an iterator that uses it's own row context. Without this explanation it's hard to know what you mean with "referring to the current row context".

**Comment by JasonWHowell** [comment]
@marcvanbreemen Can you please tell us which page you are referring to?

One tip - if you use the feedback control at the bottom of the pages to enter feedback, it should automatically add the URL of the page for context. If that's not working, we can take a look.

Thanks, Jason

**Comment by JasonWHowell** [comment]
nevermind - The DAX pages don't have the feedback control turned on, which is intentional if I recall.

**Comment by JasonWHowell** [comment]
May be related to https://learn.microsoft.com/en-us/dax/earlier-function-dax

**Comment by Minewiskan** [comment]
@marcvanbreemen - Thanks for your feedback. Unfortunately, we can't get to every user ask. The DAX reference is open source. You can contribute by creating a PR with changes you think make this clearer. Your PR will be reviewed for technical accuracy before being merged. See the [Contributing](https://github.com/MicrosoftDocs/query-docs/blob/main/CONTRIBUTING.md) to learn more. 
Thank you.
