### ISSUE TITLE
Using Ascription to Rename Columns - Bug or Spec PR Error?

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/query-docs#44]
@ehrenMSFT,

Hope you are doing well!

Regarding #42 that we just finished: Part of that PR's changes is the addition of text indicating that ascribing a new type to a table renames its columns.

True to that statement, the following work as expected:
(Tool used: Power BI Desktop October 2022)

````
let
  Data = #table({"A"}, {{1}}),
  WithNewType = Value.ReplaceType(Data, type table [Z = number])
in
 Table.Schema(WithNewType) // reports the column name as Z
 //WithNewType[Z] // works, returning column Z's values as a list
````

However, not all code paths respect this rename:
````
Table.SelectRows(WithNewType, each [Z] = 1) // doesn't work, even though the column name is now Z
//Table.SelectRows(WithNewType, each [A] = 1) // but instead the column can be referenced by its old name of A
````

Is this a mashup engine bug, or is the statement about renames that's made in the PR incorrect/incomplete?

**Comment by ehrenMSFT** [comment]
It looks like the rename applies to the table type, but not the actual records/rows of the table.

**Comment by ehrenMSFT** [comment]
And all of this is under the banner of "things you should never actually do". :)

**Comment by ehrenMSFT** [comment]
From some internal discussion, it sounds like the behavior you found may actually be a bug.

**Comment by ehrenMSFT** [comment]
We've filed a bug internally to track this. Thanks for reporting it!

**Comment by bgribaudo** [comment]
Thanks, @ehrenMSFT. 

Even though this is not the normal way to attempt renames, it will be good to have this fixed so that it doesn't inadvertently blow up someone's world...and fixing it will save from needing to figure out how to revise the PR we just did to nicely say something to the effect of "ascribing a table type kind of, sort of renames columns but can blow up the world, too, so don't even think of trying it."

**Comment by JasonWHowell** [comment]
Nudge on this thread. @ehrenMSFT did the bug get tracked, and any resolution?

**Comment by ehrenMSFT** [comment]
We've filed a bug to track it internally. We should close this issue, if possible.

**Comment by bgribaudo** [comment]
@ehrenMSFT, any idea if the bug fix here is near-term or down the road?

**Comment by ehrenMSFT** [comment]
As this doesn't seem like a high priority issue, it's likely to be down the road, if ever.

**Comment by JasonWHowell** [comment]
#please-close seems like this thread is completed. Thanks for the lively discussion.
