### ISSUE TITLE
Ascribing type table to an empty table - Bug or Spec Error?

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/query-docs#45]
Came across another point where it appears the language spec and Power BI's implementation of Power Query differ. :-)

From the language spec on [Table types](https://learn.microsoft.com/en-us/powerquery-m/m-spec-types#table-types):
> So that all table values conform to the type table, its row type is type record (the empty open record type). Thus, type table is abstract since no table value can have type table's row type (but all table values have a row type that is compatible with type table's row type). 

Based on the above, `type table` should not be ascribable to a table value, because it is abstract. However, the following works:

````
let
    Table = #table({}, {}),
    NewType = type table
in
    Value.ReplaceType(Table, NewType) // returns a table instead of erroring
````

Also, if I define a table type whose row type contains no columns but is open, the type ascription is also allowed to succeed.
````
let
    Table = #table({}, {}),
    NewType = type table[...]
in
    Value.ReplaceType(Table, NewType)
````

In contrast, attempting to ascribe `type record` (which is the equivalent of `type [...]` to an empty record fails because no record value can actually be of an open record type:
````
let
    Data = [],
    NewType = type record
in
    Value.ReplaceType(Data, NewType) // errors
````

It would seem like a similar error should be raised when attempting to ascribe `type table` to a table.

Am I misreading the spec here? Is this a mashup engine bug or does the spec's wording need to be tweaked?

**Comment by ehrenMSFT** [comment]
I can confirm the discrepancy, but I have no idea which one is correct. I'll ask around.

**Comment by ehrenMSFT** [comment]
Turns out it’s a bug in the implementation. But since it only seems to affect empty tables, we're unlikely to fix it anytime soon (or possibly ever).

**Comment by bgribaudo** [comment]
Thanks, @ehrenMSFT. That makes sense. So the language spec is correct as written on this point, but it's not worth fixing this bug because its effect will only appear in rare circumstances....
