### ISSUE TITLE
Duplicate words in statements-dax.md

### ISSUE THREAD

**Issue by ArvinZheng** [MicrosoftDocs/query-docs#67]
The following sentence has duplicate `one or more` in it, see [query-languages/dax/statements-dax.md](https://github.com/MicrosoftDocs/query-docs/blob/3c3cc65184b5de1ab59a929c0480bf57e69a4c19/query-languages/dax/statements-dax.md) for detail
> Introduces one or more one or more entity definitions that can be applied to one or more EVALUATE statements.

**Comment by Minewiskan** [comment]
@ArvinZheng - Thanks for pointing this out! We'll get it taken care of.
