### ISSUE TITLE
Clarity on Azure Synapse vs Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by awbarbeau** [MicrosoftDocs/query-docs#85]
This documentation references Azure SQL Data Warehouse support- does the APPROXIMATEDISTINCTCOUNT() function work against Azure Synapse as well? And if so, does it work for both Dedicated pools and Serverless pools?

**Comment by JasonWHowell** [comment]
Re: https://learn.microsoft.com/en-us/dax/approximate-distinctcount-function-dax

**Comment by Minewiskan** [comment]
Article will be updated 9/1/2023 PM.
